"""
Image-conditioned Klein slider training using paired gaze images.

Expects a pairs directory with files named:
  <stem>_neutral.png
  <stem>_right.png    (person looking right)
  <stem>_left.png     (person looking left)

Generated by: LivePortrait/generate_gaze_pairs.py

The slider loss is computed in packed latent space:
  gt_pred = target_pred + eta * (positive_pred - negative_pred)
where positive = right gaze, negative = left gaze.

Usage:
  python train_klein_slider_imagepairs.py \
    --model_id black-forest-labs/FLUX.2-klein-base-4B \
    --pairs_dir /path/to/gaze_pairs \
    --slider_name eye-gaze-klein \
    --output_dir ./output/eye-gaze-v2 \
    --device cuda:2
"""

import os
import gc
import copy
import glob
import random
import argparse
from contextlib import ExitStack

import cv2
import torch
import numpy as np
from PIL import Image
from tqdm.auto import tqdm
from torch.optim import AdamW
from torchvision import transforms
from diffusers.training_utils import compute_density_for_timestep_sampling
from diffusers.optimization import get_scheduler

import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from utils.model_util import load_klein_pipeline
from utils.train_util import encode_prompt_klein
from utils.lora import LoRANetwork
from utils.custom_klein_pipeline import prepare_latent_image_ids, pack_latents


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_id', type=str, default='black-forest-labs/FLUX.2-klein-base-4B')
    parser.add_argument('--pairs_dir', type=str, required=True,
                        help='directory with <stem>_neutral/right/left.png files')
    parser.add_argument('--target_prompt', type=str, default='a photo of a person',
                        help='prompt describing the neutral subject')
    parser.add_argument('--positive_prompt', type=str,
                        default='a photo of a person looking to the right',
                        help='prompt for positive concept (right gaze)')
    parser.add_argument('--negative_prompt', type=str,
                        default='a photo of a person looking to the left',
                        help='prompt for negative concept (left gaze)')
    parser.add_argument('--slider_name', type=str, default='eye-gaze-klein')
    parser.add_argument('--output_dir', type=str, default='./output/eye-gaze-v2')
    parser.add_argument('--max_train_steps', type=int, default=500)
    parser.add_argument('--lr', type=float, default=2e-3)
    parser.add_argument('--rank', type=int, default=16)
    parser.add_argument('--alpha', type=float, default=1.0)
    parser.add_argument('--eta', type=float, default=2.0)
    parser.add_argument('--train_method', type=str, default='xattn', choices=['xattn', 'full'])
    parser.add_argument('--height', type=int, default=512)
    parser.add_argument('--width', type=int, default=512)
    parser.add_argument('--num_inference_steps', type=int, default=28)
    parser.add_argument('--max_sequence_length', type=int, default=512)
    parser.add_argument('--save_every', type=int, default=100)
    parser.add_argument('--device', type=str, default='cuda:0')
    parser.add_argument('--seed', type=int, default=42)
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Dataset helpers
# ---------------------------------------------------------------------------

def load_pairs(pairs_dir):
    """Find all (neutral, right, left) triplets in pairs_dir."""
    neutrals = sorted(glob.glob(os.path.join(pairs_dir, '*_neutral.png')))
    if not neutrals:
        raise FileNotFoundError(f"No *_neutral.png found in {pairs_dir}")
    pairs = []
    for n_path in neutrals:
        stem = os.path.basename(n_path).replace('_neutral.png', '')
        r_path = os.path.join(pairs_dir, f'{stem}_right.png')
        l_path = os.path.join(pairs_dir, f'{stem}_left.png')
        if os.path.exists(r_path) and os.path.exists(l_path):
            pairs.append((n_path, r_path, l_path))
        else:
            print(f"  warning: missing right/left for {stem}, skipping.")
    if not pairs:
        raise FileNotFoundError("No complete triplets found.")
    print(f"Found {len(pairs)} image triplet(s).")
    return pairs


def load_image_tensor(path, height, width):
    """Load an image and return a float tensor in [-1, 1] with shape (1, 3, H, W)."""
    img = Image.open(path).convert('RGB').resize((width, height), Image.LANCZOS)
    t = transforms.ToTensor()(img)         # [0, 1], (3, H, W)
    t = t * 2.0 - 1.0                       # [-1, 1]
    return t.unsqueeze(0)                   # (1, 3, H, W)


@torch.no_grad()
def encode_images(vae, pairs, height, width, device, dtype):
    """VAE-encode all image triplets. Returns list of (neutral, right, left) latent tensors."""
    print("VAE-encoding image pairs ...")
    encoded = []
    for n_path, r_path, l_path in pairs:
        triplet = []
        for path in (n_path, r_path, l_path):
            img = load_image_tensor(path, height, width).to(device, dtype=dtype)
            latent = vae.encode(img).latent_dist.sample()
            latent = latent * vae.config.get('scaling_factor', 0.18215)
            triplet.append(latent)
        encoded.append(tuple(triplet))
        print(f"  encoded {os.path.basename(n_path)}")
    return encoded


# ---------------------------------------------------------------------------
# Noise addition for flow matching
# ---------------------------------------------------------------------------

def add_flow_noise(latent, noise, sigma):
    """x_t = (1 - sigma) * x_0 + sigma * noise  (flow matching interpolation)."""
    return (1.0 - sigma) * latent + sigma * noise


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    device = args.device
    weight_dtype = torch.bfloat16

    if args.seed is not None:
        torch.manual_seed(args.seed)
        random.seed(args.seed)
        np.random.seed(args.seed)

    os.makedirs(args.output_dir, exist_ok=True)

    pairs = load_pairs(args.pairs_dir)

    print(f"Loading models from {args.model_id} ...")
    pipe = load_klein_pipeline(args.model_id, weight_dtype=weight_dtype)
    transformer = pipe.transformer
    vae = pipe.vae
    text_encoder = pipe.text_encoder
    tokenizer = pipe.tokenizer
    scheduler = pipe.scheduler

    vae.to(device)
    transformer.to(device)
    text_encoder.to(device)

    # Latent geometry
    VAE_SCALE = 2 ** len(vae.config.block_out_channels)
    LATENT_C = transformer.config.in_channels // 4
    latent_h = args.height // VAE_SCALE
    latent_w = args.width // VAE_SCALE
    bsz = 1
    image_seq_len = (latent_h // 2) * (latent_w // 2)

    def calculate_shift(seq_len):
        cfg = scheduler.config
        base_seq = getattr(cfg, 'base_image_seq_len', 256)
        max_seq = getattr(cfg, 'max_image_seq_len', 4096)
        base_shift = getattr(cfg, 'base_shift', 0.5)
        max_shift = getattr(cfg, 'max_shift', 1.16)
        m = (max_shift - base_shift) / (max_seq - base_seq)
        b = base_shift - m * base_seq
        return seq_len * m + b

    mu = calculate_shift(image_seq_len)

    # Full-schedule copy for timestep lookup
    noise_scheduler_copy = copy.deepcopy(scheduler)
    noise_scheduler_copy.set_timesteps(
        noise_scheduler_copy.config.num_train_timesteps, device=device, mu=mu
    )

    # VAE encode all pairs
    encoded_pairs = encode_images(vae, pairs, args.height, args.width, device, weight_dtype)

    # Pack each encoded latent
    packed_pairs = []
    for n_lat, r_lat, l_lat in encoded_pairs:
        packed_pairs.append((
            pack_latents(n_lat, bsz, LATENT_C, latent_h, latent_w),
            pack_latents(r_lat, bsz, LATENT_C, latent_h, latent_w),
            pack_latents(l_lat, bsz, LATENT_C, latent_h, latent_w),
        ))

    print("Encoding prompts ...")
    with torch.no_grad():
        all_embeds = encode_prompt_klein(
            tokenizer, text_encoder,
            [args.target_prompt, args.positive_prompt, args.negative_prompt],
            max_sequence_length=args.max_sequence_length,
            device=device,
        )
        target_embeds, positive_embeds, negative_embeds = all_embeds.chunk(3)

    latent_image_ids = prepare_latent_image_ids(bsz, latent_h, latent_w, device, weight_dtype)
    txt_ids = torch.zeros(bsz, target_embeds.shape[1], 4, device=device, dtype=weight_dtype)

    print(f"Setting up LoRA (rank={args.rank}, method={args.train_method}) ...")
    network = LoRANetwork(
        transformer,
        rank=args.rank,
        multiplier=1.0,
        alpha=args.alpha,
        train_method=args.train_method,
    ).to(device, dtype=weight_dtype)

    optimizer = AdamW(network.prepare_optimizer_params(), lr=args.lr)
    optimizer.zero_grad()

    lr_scheduler = get_scheduler(
        'constant',
        optimizer=optimizer,
        num_warmup_steps=min(200, args.max_train_steps // 5),
        num_training_steps=args.max_train_steps,
    )

    weighting_scheme = 'none'
    logit_mean, logit_std, mode_scale = 0.0, 1.0, 1.29
    losses = []
    progress_bar = tqdm(range(args.max_train_steps), desc="Training")

    for step in range(args.max_train_steps):
        # Sample random image triplet
        pair_idx = random.randint(0, len(packed_pairs) - 1)
        neutral_packed, right_packed, left_packed = packed_pairs[pair_idx]

        # Sample timestep
        u = compute_density_for_timestep_sampling(
            weighting_scheme=weighting_scheme,
            batch_size=bsz,
            logit_mean=logit_mean,
            logit_std=logit_std,
            mode_scale=mode_scale,
        )
        indices = (u * noise_scheduler_copy.config.num_train_timesteps).long()
        timesteps = noise_scheduler_copy.timesteps[indices].to(device=device)

        # sigma for noise level (flow matching: sigma = t / T, approximately)
        sigma = noise_scheduler_copy.sigmas[indices[0].item()].to(device=device, dtype=weight_dtype)

        # Add noise to each latent
        noise = torch.randn_like(neutral_packed,
                                 generator=torch.Generator().manual_seed(args.seed + step))
        noisy_neutral = add_flow_noise(neutral_packed, noise, sigma)
        noisy_right = add_flow_noise(right_packed, noise, sigma)
        noisy_left = add_flow_noise(left_packed, noise, sigma)

        def transformer_forward(packed_latent, embeds):
            noise_pred = transformer(
                hidden_states=packed_latent,
                timestep=timesteps / 1000,
                encoder_hidden_states=embeds,
                img_ids=latent_image_ids,
                txt_ids=txt_ids,
                return_dict=False,
            )[0]
            return noise_pred[:, :packed_latent.size(1)]

        # LoRA forward on noisy neutral
        with ExitStack() as stack:
            stack.enter_context(network)
            model_pred = transformer_forward(noisy_neutral, target_embeds)

        # Frozen reference forwards
        with torch.no_grad():
            target_pred = transformer_forward(noisy_neutral, target_embeds)
            positive_pred = transformer_forward(noisy_right, positive_embeds)
            negative_pred = transformer_forward(noisy_left, negative_embeds)

            gt_pred = target_pred + args.eta * (positive_pred - negative_pred)
            gt_pred = (gt_pred / gt_pred.norm()) * positive_pred.norm()

        loss = torch.mean(
            ((model_pred.float() - gt_pred.float()) ** 2).reshape(gt_pred.shape[0], -1), 1
        ).mean()

        loss.backward()
        losses.append(loss.item())

        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()

        progress_bar.update(1)
        progress_bar.set_postfix(
            loss=f"{loss.item():.4f}",
            lr=f"{lr_scheduler.get_last_lr()[0]:.6f}",
            pair=pair_idx,
        )

        if (step + 1) % args.save_every == 0 or (step + 1) == args.max_train_steps:
            save_path = os.path.join(args.output_dir, f"{args.slider_name}_step{step+1}.pt")
            network.save_weights(save_path, dtype=weight_dtype)
            print(f"\nSaved checkpoint: {save_path}")

    print("\nTraining complete.")
    print(f"Final avg loss (last 50 steps): {np.mean(losses[-50:]):.4f}")


if __name__ == '__main__':
    main()
