transformer_path: "models/klein-9b/flux-2-klein-9b.safetensors"
vae_path: "models/klein-9b/ae.safetensors"
te_path: "Qwen/Qwen3-8B"
device: "cuda:3"
neg_image_dir: "data/eye_gaze_v7/neg/"
pos_image_dir: "data/eye_gaze_v7/pos/"
neutral_image_dir: "data/eye_gaze_v7/neutral/"
prompt: "a person"

rank: 64
alpha: 1
train_method: "xattn"
lr: 0.001
eta: 10
max_train_steps: 8000
sample_every: 500
height: 512
width: 512

output_dir: "outputs/eye_gaze_v7c"
